### ISSUE TITLE
Error in plot stage when run Tree2gd_test

### ISSUE THREAD

**Issue by ardy20** [Dee-chen/Tree2gd#16]
Dear Sir

I get the following error at plotting stage when I run: Tree2gd_test

Traceback (most recent call last):
  File "/home/user/miniconda3/bin/Tree2gd", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/lib/python3.9/site-packages/tree2gd_main.py", line 297, in main
    run_plot(step6out,args,cf)
  File "/home/user/miniconda3/lib/python3.9/site-packages/tree2gd/plot.py", line 62, in run_plot
    file_names = os.listdir("html_plot_in")
FileNotFoundError: [Errno 2] No such file or directory: 'html_plot_in'

**Comment by Dee-chen** [comment]
According to your error, the most likely cause is that the packages required for the R script in step 6 are not loaded correctly.
I suggest you eliminate the problem from the following points:
1 Determine the network connection of the server.
2 Jump to the sixth step folder of the test folder and run "Rscript Tree2GD_draw. R" to view the log file. Check whether any packages failed to install or load. If the above conditions exist, you can try to modify the image and download it (the first few lines of Tree2GD_draw. R).
3 If the package is loaded successfully but other errors occur, please send the R log to me to eliminate other errors.

**Comment by ardy20** [comment]
Thanks
I run  Rscript Tree2GD_draw.R

The error
Installing package into ‘/opt/R/local/lib’
(as ‘lib’ is unspecified)
Warning in install.packages("BiocManager") :
  'lib = "/opt/R/local/lib"' is not writable
Error in install.packages("BiocManager") : unable to install packages
Execution halted

**Comment by ZaakZoeng** [comment]
> Thanks I run Rscript Tree2GD_draw.R
> 
> The error Installing package into ‘/opt/R/local/lib’ (as ‘lib’ is unspecified) Warning in install.packages("BiocManager") : 'lib = "/opt/R/local/lib"' is not writable Error in install.packages("BiocManager") : unable to install packages Execution halted

Maybe this link can help you, because I have encountered the same problem before.（https://github.com/Dee-chen/Tree2gd/issues/22）
