### ISSUE TITLE
step2.MCL issues

### ISSUE THREAD

**Issue by yingchun323** [Dee-chen/Tree2gd#18]
Hello, I have a problem with this, I don't know how to solve it
 #!/bin/bash
#SBATCH --job-name=xall        ##任务名
#SBATCH --partition=low,big,smp01        ##partition 名字
#SBATCH --nodes=1              ##节点数
#SBATCH --ntasks-per-node=20   ##线程数
#SBATCH --error=xall.err         ##log文件
#SBATCH --output=xall.out        ##log文件
cd /public/home/zhangyingchun/data/SY_grapegenome/allX.pep
source /public/home/zhangyingchun/anaconda3/bin/activate Tree2gd
Tree2gd -i /public/home/zhangyingchun/data/SY_grapegenome/allX.pep -tree /public/home/zhangyingchun/data/SY_grapegenome/allX.pep/SY.tree -t 20 

Traceback (most recent call last):
  File "/public/home/zhangyingchun/anaconda3/envs/Tree2gd/bin/Tree2gd", line 8, in <module>
    sys.exit(main())
  File "/public/home/zhangyingchun/anaconda3/envs/Tree2gd/lib/python3.8/site-packages/tree2gd_main.py", line 239, in main
    run_tree2gd(step1out,args,cf,step2out,step4out)
  File "/public/home/zhangyingchun/anaconda3/envs/Tree2gd/lib/python3.8/site-packages/tree2gd/wgd.py", line 118, in run_tree2gd
    fa_list=mcl2fasta(int(minimal_taxa),os.sep.join([step4out,'all_fa/']),step2out,step1out,args)
  File "/public/home/zhangyingchun/anaconda3/envs/Tree2gd/lib/python3.8/site-packages/tree2gd/wgd.py", line 24, in mcl2fasta
    with open(os.sep.join([step2out,'allmcl.out.OGs.group']),"rU") as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/zhangyingchun/data/SY_grapegenome/allX.pep/output/step2.MCL/allmcl.out.OGs.group'

**Comment by manoharbisht1998** [comment]
Hey, 

Did you resolve this?

**Comment by ZaakZoeng** [comment]
Maybe the tips can help you!

https://github.com/Dee-chen/Tree2gd/issues/23
