### ISSUE TITLE
Initail and STEP5 ERROR IN TEST RUN

### ISSUE THREAD

**Issue by PRTGRWL** [Dee-chen/Tree2gd#6]
Hi..

I am using  Tree2GD:A pipeline for WGD V1.0.41 version.
I am working on example_data.

Firstly just for information regarding **initial ERROR** which was resolved manually 
Initial Error explained:- I got an Error of permission denied when pipelines moves towards using software. So I have to manually provide permission to all the tools in software by chmod 777. Then the pipelines moves forward

**Second ERROR : At step 5**

 Start gene pairs kaks calculation.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/preeti.agarwal/anaconda3/envs/t2g/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/preeti.agarwal/anaconda3/envs/t2g/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/preeti.agarwal/.local/lib/python3.8/site-packages/tree2gd/kaks.py", line 84, in run_ks
    sub_sh(args[0],args[1],args[2],args[3],args[4],args[5],args[6])
  File "/home/preeti.agarwal/.local/lib/python3.8/site-packages/tree2gd/kaks.py", line 123, in sub_sh
    Fasta2AXT(pair[2]+"-"+pair[3]+".filted.cds_aln",pair[2]+"-"+pair[3]+".cds_aln.axt")
  File "/home/preeti.agarwal/.local/lib/python3.8/site-packages/tree2gd/kaks.py", line 137, in Fasta2AXT
    for s in read_fasta_file(input):
  File "/home/preeti.agarwal/.local/lib/python3.8/site-packages/tree2gd/seq.py", line 63, in read_fasta_file
    fl = open(filename,"r")
FileNotFoundError: [Errno 2] No such file or directory: 'evm.model.supercontig_85.105-evm.model.supercontig_85.106.filted.cds_aln'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/preeti.agarwal/.local/bin/Tree2gd", line 8, in <module>
    sys.exit(main())
  File "/home/preeti.agarwal/.local/lib/python3.8/site-packages/tree2gd_main.py", line 268, in main
    run_kaks(sp_list,step1out,args,cf,step4out,step5out,gene_pairs_idmap)
  File "/home/preeti.agarwal/.local/lib/python3.8/site-packages/tree2gd/kaks.py", line 63, in run_kaks
    sh_pool.map(run_ks,arg_list)
  File "/home/preeti.agarwal/anaconda3/envs/t2g/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/preeti.agarwal/anaconda3/envs/t2g/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'evm.model.supercontig_85.105-evm.model.supercontig_85.106.filted.cds_aln'
(END)

Here to mention that I am using syntax **$Tree2gd_test** only.
Then why am I getting this error

**Comment by Dee-chen** [comment]
Hello, after checking, the problem you reported should be due to the fact that trimAl software is not installed.
In v1.0.41 of Tree2gd, I added the function of using trimAl to filter the sequence alignment results. Unlike other software, I have not added the precompiled trimAl in the Tree2gd installation package.
At present, you can use conda to install trimAl, or download the pre compiled version I just uploaded and add it to your PATH（ https://github.com/Dee-chen/Tree2gd/tree/master/tree2gd/software/trimal )。 After that, it can be used normally.

I'll be fixing the bugs I've collected so far in the near future, uploading a full new version of Tree2gd in a few days, and then you'll be able to use Tree2gd normally through pypi updates.

Again, I'm sorry for causing you trouble with Tree2gd analysis.

**Comment by PRTGRWL** [comment]
Thank you so much for the quick response.  As per your suggestion, right now , I installed Trimal through conda and it is working fine now.
